/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AntennasRouteImport } from './routes/antennas'
import { Route as AtaRouteImport } from './routes/ata'
import { Route as CbsRouteImport } from './routes/cbs'
import { Route as PanelsRouteImport } from './routes/panels'
import { Route as ResetsRouteImport } from './routes/resets'
import { Route as AtaIdRouteImport } from './routes/ata_.$id'
import { Route as PanelsIdRouteImport } from './routes/panels_.$id'
import { Route as ResetsIdRouteImport } from './routes/resets_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AntennasRoute = AntennasRouteImport.update({
  id: '/antennas',
  path: '/antennas',
  getParentRoute: () => rootRouteImport,
} as any)
const AtaRoute = AtaRouteImport.update({
  id: '/ata',
  path: '/ata',
  getParentRoute: () => rootRouteImport,
} as any)
const CbsRoute = CbsRouteImport.update({
  id: '/cbs',
  path: '/cbs',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelsRoute = PanelsRouteImport.update({
  id: '/panels',
  path: '/panels',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetsRoute = ResetsRouteImport.update({
  id: '/resets',
  path: '/resets',
  getParentRoute: () => rootRouteImport,
} as any)
const AtaIdRoute = AtaIdRouteImport.update({
  id: '/ata_/$id',
  path: '/ata/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelsIdRoute = PanelsIdRouteImport.update({
  id: '/panels_/$id',
  path: '/panels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetsIdRoute = ResetsIdRouteImport.update({
  id: '/resets_/$id',
  path: '/resets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antennas': typeof AntennasRoute
  '/ata': typeof AtaRoute
  '/cbs': typeof CbsRoute
  '/panels': typeof PanelsRoute
  '/resets': typeof ResetsRoute
  '/ata/$id': typeof AtaIdRoute
  '/panels/$id': typeof PanelsIdRoute
  '/resets/$id': typeof ResetsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antennas': typeof AntennasRoute
  '/ata': typeof AtaRoute
  '/cbs': typeof CbsRoute
  '/panels': typeof PanelsRoute
  '/resets': typeof ResetsRoute
  '/ata/$id': typeof AtaIdRoute
  '/panels/$id': typeof PanelsIdRoute
  '/resets/$id': typeof ResetsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antennas': typeof AntennasRoute
  '/ata': typeof AtaRoute
  '/cbs': typeof CbsRoute
  '/panels': typeof PanelsRoute
  '/resets': typeof ResetsRoute
  '/ata_/$id': typeof AtaIdRoute
  '/panels_/$id': typeof PanelsIdRoute
  '/resets_/$id': typeof ResetsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antennas'
    | '/ata'
    | '/cbs'
    | '/panels'
    | '/resets'
    | '/ata/$id'
    | '/panels/$id'
    | '/resets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antennas'
    | '/ata'
    | '/cbs'
    | '/panels'
    | '/resets'
    | '/ata/$id'
    | '/panels/$id'
    | '/resets/$id'
  id:
    | '__root__'
    | '/'
    | '/antennas'
    | '/ata'
    | '/cbs'
    | '/panels'
    | '/resets'
    | '/ata_/$id'
    | '/panels_/$id'
    | '/resets_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntennasRoute: typeof AntennasRoute
  AtaRoute: typeof AtaRoute
  CbsRoute: typeof CbsRoute
  PanelsRoute: typeof PanelsRoute
  ResetsRoute: typeof ResetsRoute
  AtaIdRoute: typeof AtaIdRoute
  PanelsIdRoute: typeof PanelsIdRoute
  ResetsIdRoute: typeof ResetsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antennas': {
      id: '/antennas'
      path: '/antennas'
      fullPath: '/antennas'
      preLoaderRoute: typeof AntennasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ata': {
      id: '/ata'
      path: '/ata'
      fullPath: '/ata'
      preLoaderRoute: typeof AtaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbs': {
      id: '/cbs'
      path: '/cbs'
      fullPath: '/cbs'
      preLoaderRoute: typeof CbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panels': {
      id: '/panels'
      path: '/panels'
      fullPath: '/panels'
      preLoaderRoute: typeof PanelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resets': {
      id: '/resets'
      path: '/resets'
      fullPath: '/resets'
      preLoaderRoute: typeof ResetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ata_/$id': {
      id: '/ata_/$id'
      path: '/ata/$id'
      fullPath: '/ata/$id'
      preLoaderRoute: typeof AtaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panels_/$id': {
      id: '/panels_/$id'
      path: '/panels/$id'
      fullPath: '/panels/$id'
      preLoaderRoute: typeof PanelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resets_/$id': {
      id: '/resets_/$id'
      path: '/resets/$id'
      fullPath: '/resets/$id'
      preLoaderRoute: typeof ResetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntennasRoute: AntennasRoute,
  AtaRoute: AtaRoute,
  CbsRoute: CbsRoute,
  PanelsRoute: PanelsRoute,
  ResetsRoute: ResetsRoute,
  AtaIdRoute: AtaIdRoute,
  PanelsIdRoute: PanelsIdRoute,
  ResetsIdRoute: ResetsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
